# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoalKeeper.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 4, 18, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 5, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 6, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 7, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 8, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 9, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 10, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 11, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 12, 1, 1, 2)
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 13, 1, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 14, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 15, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(9)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 16, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 17, 0, 1, 4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(30)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Supporter v0.1"))
        self.label.setText(_translate("MainWindow", "SIMS ID"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "ServiceNow View URL"))
        self.label_4.setText(_translate("MainWindow", "Assign"))
        self.comboBox.setItemText(0, _translate("MainWindow", "After"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Every"))
        self.label_5.setText(_translate("MainWindow", "mins"))
        self.label_6.setText(_translate("MainWindow", "Assign to"))
        self.checkBox.setText(_translate("MainWindow", "Kevin Song"))
        self.checkBox_2.setText(_translate("MainWindow", "Dean Shi"))
        self.checkBox_3.setText(_translate("MainWindow", "Jia Liu"))
        self.checkBox_4.setText(_translate("MainWindow", "Andy Jia"))
        self.checkBox_5.setText(_translate("MainWindow", "Jenny Chen"))
        self.checkBox_6.setText(_translate("MainWindow", "Stacey Huang"))
        self.checkBox_7.setText(_translate("MainWindow", "Faye Zhao"))
        self.checkBox_8.setText(_translate("MainWindow", "Zoe Duan"))
        self.checkBox_9.setText(_translate("MainWindow", "Christiano Gui"))
        self.checkBox_10.setText(_translate("MainWindow", "Lorenzo Qi"))
        self.checkBox_11.setText(_translate("MainWindow", "Leo Zhang"))
        self.checkBox_12.setText(_translate("MainWindow", "Alex Zhang"))
        self.checkBox_13.setText(_translate("MainWindow", "Anna Wu"))
        self.pushButton.setText(_translate("MainWindow", "Launch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "GoalKeeper"))
        self.label_7.setText(_translate("MainWindow", "In development..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "In development..."))
